receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    traces_endpoint: $SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
